CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  studentId INTEGER NOT NULL,
  email TEXT NOT NULL,
  color TEXT NOT NULL,
  size TEXT NOT NULL,
  paymentId TEXT NOT NULL,
  createdAt TEXT NOT NULL
);